#[derive(Debug, PartialEq, Clone)]
pub enum Building {
    // NE
    TreeOfLife,
    TreeOfAges,
    TreeOfEternity,
    AltarOfElders,
    MoonWell,
    AncientOfWar,
    AncientOfWonders,
    HuntersHall,
    AncientProtector,
    AncientOfWind,
    AncientOfLore,
    ChimaeraRoot,
    // OR
    GreatHall,
    StrongHold,
    Fortress,
    AltarOfStorms,
    Burrow,
    ReinforcedBurrow,
    OrcBarracks,
    WarMill,
    WatchTower,
    VoodooLounge,
    SpiritLodge,
    Beastiary,
    TaurenTotem,
    // HU
    Farm,
    AltarofKings,
    Workshop,
    ArcaneSanctum,
    HumanBarracks,
    Blacksmith,
    GryphonAviary,
    ScoutTower,
    ArcaneVault,
    LumberMill,
    TownHall,
    Keep,
    Castle,
    CannonTower,
    GuardTower,
    ArcaneTower,
    // UD
    AltarOfDarkness,
    Necropolis,
    Crypt,
    TempleOfTheDamned,
    TombofRelics,
    HauntedGoldMine,
    Ziggurat,
    Boneyard,
    SacrificialPit,
    Slaughterhouse,
    Graveyard,
    HallsOfTheDead,
    BlackCitadel,
    SpiritTower,
    NerubianTower,
    // Neutral
    Tavern,
    MercernaryCamp,
}

impl Building {
    pub(crate) fn from_str(str: &str) -> Option<Building> {
        match str {
            // NE
            "etol" => Some(Building::TreeOfLife),
            "etoa" => Some(Building::TreeOfAges),
            "etoe" => Some(Building::TreeOfEternity),
            "eate" => Some(Building::AltarOfElders),
            "emow" => Some(Building::MoonWell),
            "eaom" => Some(Building::AncientOfWar),
            "eden" => Some(Building::AncientOfWonders),
            "edob" => Some(Building::HuntersHall),
            "etrp" => Some(Building::AncientProtector),
            "eaow" => Some(Building::AncientOfWind),
            "eaoe" => Some(Building::AncientOfLore),
            "edos" => Some(Building::ChimaeraRoot),
            // OR
            "ogre" => Some(Building::GreatHall),
            "ostr" => Some(Building::StrongHold),
            "ofrt" => Some(Building::Fortress),
            "oalt" => Some(Building::AltarOfStorms),
            "otrb" => Some(Building::Burrow),
            "orbr" => Some(Building::ReinforcedBurrow),
            "obar" => Some(Building::OrcBarracks),
            "ofor" => Some(Building::WarMill),
            "owtw" => Some(Building::WatchTower),
            "ovln" => Some(Building::VoodooLounge),
            "osld" => Some(Building::SpiritLodge),
            "obea" => Some(Building::Beastiary),
            "otto" => Some(Building::TaurenTotem),
            // HU
            "hhou" => Some(Building::Farm),
            "halt" => Some(Building::AltarofKings),
            "harm" => Some(Building::Workshop),
            "hars" => Some(Building::ArcaneSanctum),
            "hbar" => Some(Building::HumanBarracks),
            "hbla" => Some(Building::Blacksmith),
            "hgra" => Some(Building::GryphonAviary),
            "hwtw" => Some(Building::ScoutTower),
            "hvlt" => Some(Building::ArcaneVault),
            "hlum" => Some(Building::LumberMill),
            "htow" => Some(Building::TownHall),
            "hkee" => Some(Building::Keep),
            "hcas" => Some(Building::Castle),
            "hctw" => Some(Building::CannonTower),
            "hgtw" => Some(Building::GuardTower),
            "hatw" => Some(Building::ArcaneTower),
            // UD
            "uaod" => Some(Building::AltarOfDarkness),
            "unpl" => Some(Building::Necropolis),
            "usep" => Some(Building::Crypt),
            "utod" => Some(Building::TempleOfTheDamned),
            "utom" => Some(Building::TombofRelics),
            "ugol" => Some(Building::HauntedGoldMine),
            "uzig" => Some(Building::Ziggurat),
            "ubon" => Some(Building::Boneyard),
            "usap" => Some(Building::SacrificialPit),
            "uslh" => Some(Building::Slaughterhouse),
            "ugrv" => Some(Building::Graveyard),
            "unp1" => Some(Building::HallsOfTheDead),
            "unp2" => Some(Building::BlackCitadel),
            "uzg1" => Some(Building::SpiritTower),
            "uzg2" => Some(Building::NerubianTower),
            // Neutral
            "nmer" => Some(Building::MercernaryCamp),
            "ntav" => Some(Building::Tavern),
            _ => None,
        }
    }
}

#[derive(Debug, Clone, PartialEq)]
pub enum Upgrade {
    ControlMagic,
    Swords,
    Gunpowder,
    Plating,
    HumanArmor,
    Masonry,
    FlyingMachineBombs,
    LumberHarvesting,
    Defend,
    AnimalWarTraining,
    PriestTraining,
    SorceressTraining,
    LongRifles,
    MagicSentry,
    Flare,
    StormHammers,
    Barrage,
    HumanBackpack,
    FlakCannons,
    FragmentationShards,
    Cloud,
    StrengthOfTheMoon,
    StrengthOfTheWild,
    MoonArmor,
    ReinforcedHides,
    Ultravision,
    NaturesBlessing,
    ImprovedBows,
    Marksmanship,
    Sentinel,
    UpgradeMoonGlaive,
    DruidOfTheTalonTraining,
    DruidOfTheClawTraining,
    AbolishMagic,
    HippogryphTaming,
    CorrosiveBreath,
    VorpalBlades,
    ResistantSkin,
    HardenedSkin,
    MarkOfTheClaw,
    MarkOfTheTalon,
    WellSpring,
    NightElfBackpack,
    Chaos,
    MeleeWeapons,
    RangedWeapons,
    OrcArmor,
    WarDrumsDamageIncrease,
    Pillage,
    BerserkerStrength,
    Pulverize,
    Ensnare,
    EnvenomedSpears,
    WitchDoctorTraining,
    ShamanTraining,
    SpikedBarricades,
    TrollRegeneration,
    LiquidFire,
    OrcBackpack,
    SpiritWalkerTraining,
    BerserkerUpgrade,
    ReinforcedDefenses,
    BurningOil,
    DestroyerForm,
    UnholyStrength,
    CreatureAttack,
    UnholyArmor,
    CreatureCarapace,
    Cannibalize,
    GhoulFrenzy,
    Web,
    StoneForm,
    NecromancerTraining,
    BansheeTraining,
    FreezingBreath,
    SkeletalLongevity,
    DiseaseCloud,
    SkeletalMastery,
    Burrow,
    ExhumeCorpses,
    UndeadBackpack,
}

impl Upgrade {
    pub(crate) fn from_str(str: &str) -> Option<Upgrade> {
        match str {
            "Rhss" => Some(Upgrade::ControlMagic),
            "Rhme" => Some(Upgrade::Swords),
            "Rhra" => Some(Upgrade::Gunpowder),
            "Rhar" => Some(Upgrade::Plating),
            "Rhla" => Some(Upgrade::HumanArmor),
            "Rhac" => Some(Upgrade::Masonry),
            "Rhgb" => Some(Upgrade::FlyingMachineBombs),
            "Rhlh" => Some(Upgrade::LumberHarvesting),
            "Rhde" => Some(Upgrade::Defend),
            "Rhan" => Some(Upgrade::AnimalWarTraining),
            "Rhpt" => Some(Upgrade::PriestTraining),
            "Rhst" => Some(Upgrade::SorceressTraining),
            "Rhri" => Some(Upgrade::LongRifles),
            "Rhse" => Some(Upgrade::MagicSentry),
            "Rhfl" => Some(Upgrade::Flare),
            "Rhhb" => Some(Upgrade::StormHammers),
            "Rhrt" => Some(Upgrade::Barrage),
            "Rhpm" => Some(Upgrade::HumanBackpack),
            "Rhfc" => Some(Upgrade::FlakCannons),
            "Rhfs" => Some(Upgrade::FragmentationShards),
            "Rhcd" => Some(Upgrade::Cloud),
            "Resm" => Some(Upgrade::StrengthOfTheMoon),
            "Resw" => Some(Upgrade::StrengthOfTheWild),
            "Rema" => Some(Upgrade::MoonArmor),
            "Rerh" => Some(Upgrade::ReinforcedHides),
            "Reuv" => Some(Upgrade::Ultravision),
            "Renb" => Some(Upgrade::NaturesBlessing),
            "Reib" => Some(Upgrade::ImprovedBows),
            "Remk" => Some(Upgrade::Marksmanship),
            "Resc" => Some(Upgrade::Sentinel),
            "Remg" => Some(Upgrade::UpgradeMoonGlaive),
            "Redt" => Some(Upgrade::DruidOfTheTalonTraining),
            "Redc" => Some(Upgrade::DruidOfTheClawTraining),
            "Resi" => Some(Upgrade::AbolishMagic),
            "Reht" => Some(Upgrade::HippogryphTaming),
            "Recb" => Some(Upgrade::CorrosiveBreath),
            "Repb" => Some(Upgrade::VorpalBlades),
            "Rers" => Some(Upgrade::ResistantSkin),
            "Rehs" => Some(Upgrade::HardenedSkin),
            "Reeb" => Some(Upgrade::MarkOfTheClaw),
            "Reec" => Some(Upgrade::MarkOfTheTalon),
            "Rews" => Some(Upgrade::WellSpring),
            "Repm" => Some(Upgrade::NightElfBackpack),
            "Roch" => Some(Upgrade::Chaos),
            "Rome" => Some(Upgrade::MeleeWeapons),
            "Rora" => Some(Upgrade::RangedWeapons),
            "Roar" => Some(Upgrade::OrcArmor),
            "Rwdm" => Some(Upgrade::WarDrumsDamageIncrease),
            "Ropg" => Some(Upgrade::Pillage),
            "Robs" => Some(Upgrade::BerserkerStrength),
            "Rows" => Some(Upgrade::Pulverize),
            "Roen" => Some(Upgrade::Ensnare),
            "Rovs" => Some(Upgrade::EnvenomedSpears),
            "Rowd" => Some(Upgrade::WitchDoctorTraining),
            "Rost" => Some(Upgrade::ShamanTraining),
            "Rosp" => Some(Upgrade::SpikedBarricades),
            "Rotr" => Some(Upgrade::TrollRegeneration),
            "Rolf" => Some(Upgrade::LiquidFire),
            "Ropm" => Some(Upgrade::OrcBackpack),
            "Rowt" => Some(Upgrade::SpiritWalkerTraining),
            "Robk" => Some(Upgrade::BerserkerUpgrade),
            "Rorb" => Some(Upgrade::ReinforcedDefenses),
            "Robf" => Some(Upgrade::BurningOil),
            "Rusp" => Some(Upgrade::DestroyerForm),
            "Rume" => Some(Upgrade::UnholyStrength),
            "Rura" => Some(Upgrade::CreatureAttack),
            "Ruar" => Some(Upgrade::UnholyArmor),
            "Rucr" => Some(Upgrade::CreatureCarapace),
            "Ruac" => Some(Upgrade::Cannibalize),
            "Rugf" => Some(Upgrade::GhoulFrenzy),
            "Ruwb" => Some(Upgrade::Web),
            "Rusf" => Some(Upgrade::StoneForm),
            "Rune" => Some(Upgrade::NecromancerTraining),
            "Ruba" => Some(Upgrade::BansheeTraining),
            "Rufb" => Some(Upgrade::FreezingBreath),
            "Rusl" => Some(Upgrade::SkeletalLongevity),
            "Rupc" => Some(Upgrade::DiseaseCloud),
            "Rusm" => Some(Upgrade::SkeletalMastery),
            "Rubu" => Some(Upgrade::Burrow),
            "Ruex" => Some(Upgrade::ExhumeCorpses),
            "Rupm" => Some(Upgrade::UndeadBackpack),
            _ => None,
        }
    }
}
