#[derive(Debug, PartialEq, Clone)]
pub enum Item {
    AmuletOfRecall,
    AnkhOfReincarnation,
    BootsOfQuelThalas6,
    BeltOfGiantStrength6,
    BootsOfSpeed,
    ScepterOfMastery,
    RobeOfTheMagi6,
    CrownOfKings5,
    CloakOfShadows,
    CrystalBall,
    KelensDaggerOfEscape,
    GemOfTrueSeeing,
    GoblinLandMines,
    SoulGem,
    GlyphOfUltravision,
    GlyphOfFortification,
    Soul,
    MedusaPebble,
    SlippersOfAgility3,
    ClawsOfAttack3,
    MantleOfIntelligence3,
    RingOfProtection2,
    RingOfProtection3,
    RingOfProtection4,
    KhadgarsGemOfHealth,
    GauntletsOfOgreStrength3,
    OrbOfFire,
    OrbOfFrost,
    OrbOfLightning,
    OrbOfVenom,
    OrbOfDarkness,
    OrbOfCorruption,
    PotionOfDivinity,
    PotionOfHealing,
    PotionOfGreaterHealing,
    PotionOfInvisibility,
    PotionOfGreaterInvisibility,
    PotionOfMana,
    PotionOfGreaterMana,
    PotionOfInvulnerability,
    PotionOfLesserInvulnerability,
    PotionOfRestoration,
    PotionOfSpeed,
    RingOfRegeneration,
    SobiMask,
    HornOfTheClouds,
    ScrollOfHealing,
    ScrollOfMana,
    ScrollOfProtection,
    ScrollOfRestoration,
    StaffOfSilence,
    ScrollOfTownPortal,
    GoblinNightScope,
    TomeOfAgility,
    TomeOfExperience,
    TomeOfIntelligence,
    TomeOfPower,
    TomeOfStrength,
    WarsongBattleDrums,
    WandOfIllusion,
    WandOfNegation,
    RuneOfDispelMagic,
    RuneOfTheWatcher,
    RedDrakeEgg,
    StoneToken,
    DemonicFigurine,
    SpikedCollar,
    BookOfTheDead,
    EnchantedGemstone,
    Mooncrystal,
    MaskOfDeath,
    ScrollOfAnimateDead,
    ScrollOfResurrection,
    ScrollOfTheBeast,
    InfernoStone,
    IceShard,
    AmuletOfTheWild,
    SentryWards,
    HealingWards,
    WandOfLightningShield,
    WandOfTheWind,
    RodOfNecromancy,
    AntiMagicPotion,
    CloakOfFlames,
    TalismanOfEvasion,
    NecklaceOfSpellImmunity,
    TheLionHornOfStormwind,
    KhadgarsPipeOfInsight,
    ScourgeBoneChimes,
    AlleriasFluteOfAccuracy,
    AncientJanggoOfEndurance,
    LegionDoomHorn,
    HoodOfCunning,
    MedallionOfCourage,
    HelmOfValor,
    CircletOfNobility,
    PeriaptOfVitality,
    TomeOfGreaterExperience,
    ManaStone,
    HealthStone,
    TomeOfKnowledge,
    TomeOfStrength2,
    TomeOfIntelligence2,
    TomeOfAgility2,
    RingOfProtection1,
    RingOfProtection5,
    ClawsOfAttack6,
    ClawsOfAttack9,
    ClawsOfAttack12,
    ClawsOfAttack15,
    ManualOfHealth,
    PendantOfMana,
    PendantOfEnergy,
    GlovesOfHaste,
    TalismanOfTheWild,
    PhatLewt,
    GlyphOfPurification,
    Cheese,
    MaulOfStrength,
    RingOfSuperiority,
    BracerOfAgility,
    SkullShield,
    VoodooDoll,
    SpiderRing,
    TotemOfMight,
    AncientFigurine,
    LionsRing,
    IronwoodBranch,
    JadeRing,
    DruidPouch,
    HealingSalve,
    ClarityPotion,
    LesserClarityPotion,
    MinorReplenishmentPotion,
    LesserReplenishmentPotion,
    ReplenishmentPotion,
    GreaterReplenishmentPotion,
    LesserScrollOfReplenishment,
    GreaterScrollOfReplenishment,
    ScrollOfRegeneration,
    GoldCoins,
    BundleOfLumber,
    FlareGun,
    PotionOfOmniscience,
    GlyphOfOmniscience,
    WandOfNeutralization,
    SpiderSilkBroach,
    MonsterLure,
    SacrificialSkull,
    Moonstone,
    RunedBracers,
    VampiricPotion,
    WandOfManaStealing,
    TinyCastle,
    TinyGreatHall,
    IvoryTower,
    WandOfShadowsight,
    TomeOfRetraining,
    StaffOfNegation,
    StaffOfTeleportation,
    StaffOfPreservation,
    MechanicalCritter,
    AmuletOfSpellShield,
    SpellBook,
    StaffOfSanctuary,
    ScrollOfSpeed,
    DustOfAppearance,
    OrbOfSlow,
    DiamondOfSummoning,
    ShadowOrb1,
    ShadowOrb2,
    ShadowOrb3,
    ShadowOrb4,
    ShadowOrb5,
    ShadowOrb6,
    ShadowOrb7,
    ShadowOrb8,
    ShadowOrb9,
    ShadowOrb10,
    ShadowOrbFragment,
    FrostWyrmSkullShield,
    RingOfTheArchmagi,
    ShamanicTotem,
    Shimmerweed,
    BattleStandard,
    SkeletalArtifact,
    ThunderLizardEgg,
    SecretLevelPowerup,
    OrbOfKilJaeden,
    TinyBlacksmith,
    TinyFarm,
    TinyLumberMill,
    TinyBarracks,
    TinyAltarOfKings,
    MagicKeyChain,
    StaffOfReanimation,
    SacredRelic,
    HelmOfBattlethirst,
    BladebaneArmor,
    RunedGauntlets,
    FirehandGauntlets,
    GlovesOfSpellMastery,
    CrownOfTheDeathlord,
    ArcaneScroll,
    ScrollOfTheUnholyLegion,
    TomeOfSacrifices,
    DrekTharsSpellbook,
    GrimoireOfSouls,
    ArcaniteShield,
    ShieldOfTheDeathlord,
    ShieldOfHonor,
    EnchantedShield,
    ThunderlizardDiamond,
    ClockworkPenguin,
    ShimmerglazeRoast,
    BloodfeathersHeart,
    CelestialOrbOfSouls,
    ShamanClaws,
    SearingBlade,
    Frostguard,
    EnchantedVial,
    RustyMiningPick,
    MogrinsReport,
    Serathil,
    SturdyWarAxe,
    Killmaim,
    ScepterOfTheSea,
    AncestralStaff,
    Mindstaff,
    ScepterOfHealing,
    AssassinsBlade,
    KegOfAle,
    ThunderPhoenixEgg,
    KegOfThunderwater,
    ThunderbloomBulb,
}

#[derive(Debug, PartialEq, Clone)]
pub enum ItemOrSlot {
    Item(Item),
    Slot(u8),
}

impl Item {
    pub(crate) fn from_str(str: &str) -> Option<Item> {
        match str {
            "amrc" => Some(Item::AmuletOfRecall),
            "ankh" => Some(Item::AnkhOfReincarnation),
            "belv" => Some(Item::BootsOfQuelThalas6),
            "bgst" => Some(Item::BeltOfGiantStrength6),
            "bspd" => Some(Item::BootsOfSpeed),
            "ccmd" => Some(Item::ScepterOfMastery),
            "ciri" => Some(Item::RobeOfTheMagi6),
            "ckng" => Some(Item::CrownOfKings5),
            "clsd" => Some(Item::CloakOfShadows),
            "crys" => Some(Item::CrystalBall),
            "desc" => Some(Item::KelensDaggerOfEscape),
            "gemt" => Some(Item::GemOfTrueSeeing),
            "gobm" => Some(Item::GoblinLandMines),
            "gsou" => Some(Item::SoulGem),
            "guvi" => Some(Item::GlyphOfUltravision),
            "gfor" => Some(Item::GlyphOfFortification),
            "soul" => Some(Item::Soul),
            "mdpb" => Some(Item::MedusaPebble),
            "rag1" => Some(Item::SlippersOfAgility3),
            "rat3" => Some(Item::ClawsOfAttack3),
            "rin1" => Some(Item::MantleOfIntelligence3),
            "rde1" => Some(Item::RingOfProtection2),
            "rde2" => Some(Item::RingOfProtection3),
            "rde3" => Some(Item::RingOfProtection4),
            "rhth" => Some(Item::KhadgarsGemOfHealth),
            "rst1" => Some(Item::GauntletsOfOgreStrength3),
            "ofir" => Some(Item::OrbOfFire),
            "ofro" => Some(Item::OrbOfFrost),
            "olig" => Some(Item::OrbOfLightning),
            "oli2" => Some(Item::OrbOfLightning),
            "oven" => Some(Item::OrbOfVenom),
            "odef" => Some(Item::OrbOfDarkness),
            "ocor" => Some(Item::OrbOfCorruption),
            "pdiv" => Some(Item::PotionOfDivinity),
            "phea" => Some(Item::PotionOfHealing),
            "pghe" => Some(Item::PotionOfGreaterHealing),
            "pinv" => Some(Item::PotionOfInvisibility),
            "pgin" => Some(Item::PotionOfGreaterInvisibility),
            "pman" => Some(Item::PotionOfMana),
            "pgma" => Some(Item::PotionOfGreaterMana),
            "pnvu" => Some(Item::PotionOfInvulnerability),
            "pnvl" => Some(Item::PotionOfLesserInvulnerability),
            "pres" => Some(Item::PotionOfRestoration),
            "pspd" => Some(Item::PotionOfSpeed),
            "rlif" => Some(Item::RingOfRegeneration),
            "rwiz" => Some(Item::SobiMask),
            "sfog" => Some(Item::HornOfTheClouds),
            "shea" => Some(Item::ScrollOfHealing),
            "sman" => Some(Item::ScrollOfMana),
            "spro" => Some(Item::ScrollOfProtection),
            "sres" => Some(Item::ScrollOfRestoration),
            "ssil" => Some(Item::StaffOfSilence),
            "stwp" => Some(Item::ScrollOfTownPortal),
            "tels" => Some(Item::GoblinNightScope),
            "tdex" => Some(Item::TomeOfAgility),
            "texp" => Some(Item::TomeOfExperience),
            "tint" => Some(Item::TomeOfIntelligence),
            "tkno" => Some(Item::TomeOfPower),
            "tstr" => Some(Item::TomeOfStrength),
            "ward" => Some(Item::WarsongBattleDrums),
            "will" => Some(Item::WandOfIllusion),
            "wneg" => Some(Item::WandOfNegation),
            "rdis" => Some(Item::RuneOfDispelMagic),
            "rwat" => Some(Item::RuneOfTheWatcher),
            "fgrd" => Some(Item::RedDrakeEgg),
            "fgrg" => Some(Item::StoneToken),
            "fgdg" => Some(Item::DemonicFigurine),
            "fgfh" => Some(Item::SpikedCollar),
            "fgsk" => Some(Item::BookOfTheDead),
            "engs" => Some(Item::EnchantedGemstone),
            "k3m1" => Some(Item::Mooncrystal),
            "modt" => Some(Item::MaskOfDeath),
            "sand" => Some(Item::ScrollOfAnimateDead),
            "srrc" => Some(Item::ScrollOfResurrection),
            "sror" => Some(Item::ScrollOfTheBeast),
            "infs" => Some(Item::InfernoStone),
            "shar" => Some(Item::IceShard),
            "wild" => Some(Item::AmuletOfTheWild),
            "wswd" => Some(Item::SentryWards),
            "whwd" => Some(Item::HealingWards),
            "wlsd" => Some(Item::WandOfLightningShield),
            "wcyc" => Some(Item::WandOfTheWind),
            "rnec" => Some(Item::RodOfNecromancy),
            "pams" => Some(Item::AntiMagicPotion),
            "clfm" => Some(Item::CloakOfFlames),
            "evtl" => Some(Item::TalismanOfEvasion),
            "nspi" => Some(Item::NecklaceOfSpellImmunity),
            "lhst" => Some(Item::TheLionHornOfStormwind),
            "kpin" => Some(Item::KhadgarsPipeOfInsight),
            "sbch" => Some(Item::ScourgeBoneChimes),
            "afac" => Some(Item::AlleriasFluteOfAccuracy),
            "ajen" => Some(Item::AncientJanggoOfEndurance),
            "lgdh" => Some(Item::LegionDoomHorn),
            "hcun" => Some(Item::HoodOfCunning),
            "mcou" => Some(Item::MedallionOfCourage),
            "hval" => Some(Item::HelmOfValor),
            "cnob" => Some(Item::CircletOfNobility),
            "prvt" => Some(Item::PeriaptOfVitality),
            "tgxp" => Some(Item::TomeOfGreaterExperience),
            "mnst" => Some(Item::ManaStone),
            "hlst" => Some(Item::HealthStone),
            "tpow" => Some(Item::TomeOfKnowledge),
            "tst2" => Some(Item::TomeOfStrength2),
            "tin2" => Some(Item::TomeOfIntelligence2),
            "tdx2" => Some(Item::TomeOfAgility2),
            "rde0" => Some(Item::RingOfProtection1),
            "rde4" => Some(Item::RingOfProtection5),
            "rat6" => Some(Item::ClawsOfAttack6),
            "rat9" => Some(Item::ClawsOfAttack9),
            "ratc" => Some(Item::ClawsOfAttack12),
            "ratf" => Some(Item::ClawsOfAttack15),
            "manh" => Some(Item::ManualOfHealth),
            "pmna" => Some(Item::PendantOfMana),
            "penr" => Some(Item::PendantOfEnergy),
            "gcel" => Some(Item::GlovesOfHaste),
            "totw" => Some(Item::TalismanOfTheWild),
            "phlt" => Some(Item::PhatLewt),
            "gopr" => Some(Item::GlyphOfPurification),
            "ches" => Some(Item::Cheese),
            "mlst" => Some(Item::MaulOfStrength),
            "rnsp" => Some(Item::RingOfSuperiority),
            "brag" => Some(Item::BracerOfAgility),
            "sksh" => Some(Item::SkullShield),
            "vddl" => Some(Item::VoodooDoll),
            "sprn" => Some(Item::SpiderRing),
            "tmmt" => Some(Item::TotemOfMight),
            "anfg" => Some(Item::AncientFigurine),
            "lnrn" => Some(Item::LionsRing),
            "iwbr" => Some(Item::IronwoodBranch),
            "jdrn" => Some(Item::JadeRing),
            "drph" => Some(Item::DruidPouch),
            "hslv" => Some(Item::HealingSalve),
            "pclr" => Some(Item::ClarityPotion),
            "plcl" => Some(Item::LesserClarityPotion),
            "rej1" => Some(Item::MinorReplenishmentPotion),
            "rej2" => Some(Item::LesserReplenishmentPotion),
            "rej3" => Some(Item::ReplenishmentPotion),
            "rej4" => Some(Item::GreaterReplenishmentPotion),
            "rej5" => Some(Item::LesserScrollOfReplenishment),
            "rej6" => Some(Item::GreaterScrollOfReplenishment),
            "sreg" => Some(Item::ScrollOfRegeneration),
            "gold" => Some(Item::GoldCoins),
            "lmbr" => Some(Item::BundleOfLumber),
            "fgun" => Some(Item::FlareGun),
            "pomn" => Some(Item::PotionOfOmniscience),
            "gomn" => Some(Item::GlyphOfOmniscience),
            "wneu" => Some(Item::WandOfNeutralization),
            "silk" => Some(Item::SpiderSilkBroach),
            "lure" => Some(Item::MonsterLure),
            "skul" => Some(Item::SacrificialSkull),
            "moon" => Some(Item::Moonstone),
            "brac" => Some(Item::RunedBracers),
            "vamp" => Some(Item::VampiricPotion),
            "woms" => Some(Item::WandOfManaStealing),
            "tcas" => Some(Item::TinyCastle),
            "tgrh" => Some(Item::TinyGreatHall),
            "tsct" => Some(Item::IvoryTower),
            "wshs" => Some(Item::WandOfShadowsight),
            "tret" => Some(Item::TomeOfRetraining),
            "sneg" => Some(Item::StaffOfNegation),
            "stel" => Some(Item::StaffOfTeleportation),
            "spre" => Some(Item::StaffOfPreservation),
            "mcri" => Some(Item::MechanicalCritter),
            "spsh" => Some(Item::AmuletOfSpellShield),
            "sbok" => Some(Item::SpellBook),
            "ssan" => Some(Item::StaffOfSanctuary),
            "shas" => Some(Item::ScrollOfSpeed),
            "dust" => Some(Item::DustOfAppearance),
            "oslo" => Some(Item::OrbOfSlow),
            "dsum" => Some(Item::DiamondOfSummoning),
            "sor1" => Some(Item::ShadowOrb1),
            "sor2" => Some(Item::ShadowOrb2),
            "sor3" => Some(Item::ShadowOrb3),
            "sor4" => Some(Item::ShadowOrb4),
            "sor5" => Some(Item::ShadowOrb5),
            "sor6" => Some(Item::ShadowOrb6),
            "sor7" => Some(Item::ShadowOrb7),
            "sor8" => Some(Item::ShadowOrb8),
            "sor9" => Some(Item::ShadowOrb9),
            "sora" => Some(Item::ShadowOrb10),
            "sorf" => Some(Item::ShadowOrbFragment),
            "fwss" => Some(Item::FrostWyrmSkullShield),
            "ram1" => Some(Item::RingOfTheArchmagi),
            "ram2" => Some(Item::RingOfTheArchmagi),
            "ram3" => Some(Item::RingOfTheArchmagi),
            "ram4" => Some(Item::RingOfTheArchmagi),
            "shtm" => Some(Item::ShamanicTotem),
            "shwd" => Some(Item::Shimmerweed),
            "btst" => Some(Item::BattleStandard),
            "skrt" => Some(Item::SkeletalArtifact),
            "thle" => Some(Item::ThunderLizardEgg),
            "sclp" => Some(Item::SecretLevelPowerup),
            "gldo" => Some(Item::OrbOfKilJaeden),
            "tbsm" => Some(Item::TinyBlacksmith),
            "tfar" => Some(Item::TinyFarm),
            "tlum" => Some(Item::TinyLumberMill),
            "tbar" => Some(Item::TinyBarracks),
            "tbak" => Some(Item::TinyAltarOfKings),
            "mgtk" => Some(Item::MagicKeyChain),
            "stre" => Some(Item::StaffOfReanimation),
            "horl" => Some(Item::SacredRelic),
            "hbth" => Some(Item::HelmOfBattlethirst),
            "blba" => Some(Item::BladebaneArmor),
            "rugt" => Some(Item::RunedGauntlets),
            "frhg" => Some(Item::FirehandGauntlets),
            "gvsm" => Some(Item::GlovesOfSpellMastery),
            "crdt" => Some(Item::CrownOfTheDeathlord),
            "arsc" => Some(Item::ArcaneScroll),
            "scul" => Some(Item::ScrollOfTheUnholyLegion),
            "tmsc" => Some(Item::TomeOfSacrifices),
            "dtsb" => Some(Item::DrekTharsSpellbook),
            "grsl" => Some(Item::GrimoireOfSouls),
            "arsh" => Some(Item::ArcaniteShield),
            "shdt" => Some(Item::ShieldOfTheDeathlord),
            "shhn" => Some(Item::ShieldOfHonor),
            "shen" => Some(Item::EnchantedShield),
            "thdm" => Some(Item::ThunderlizardDiamond),
            "stpg" => Some(Item::ClockworkPenguin),
            "shrs" => Some(Item::ShimmerglazeRoast),
            "bfhr" => Some(Item::BloodfeathersHeart),
            "cosl" => Some(Item::CelestialOrbOfSouls),
            "shcw" => Some(Item::ShamanClaws),
            "srbd" => Some(Item::SearingBlade),
            "frgd" => Some(Item::Frostguard),
            "envl" => Some(Item::EnchantedVial),
            "rump" => Some(Item::RustyMiningPick),
            "mort" => Some(Item::MogrinsReport),
            "srtl" => Some(Item::Serathil),
            "stwa" => Some(Item::SturdyWarAxe),
            "klmm" => Some(Item::Killmaim),
            "rots" => Some(Item::ScepterOfTheSea),
            "axas" => Some(Item::AncestralStaff),
            "mnsf" => Some(Item::Mindstaff),
            "schl" => Some(Item::ScepterOfHealing),
            "asbl" => Some(Item::AssassinsBlade),
            "kgal" => Some(Item::KegOfAle),
            "dphe" => Some(Item::ThunderPhoenixEgg),
            "dkfw" => Some(Item::KegOfThunderwater),
            "dthb" => Some(Item::ThunderbloomBulb),
            _ => None,
        }
    }
}
